### ISSUE TITLE
Automate hosting setup

### ISSUE THREAD

**Issue by ianmuchina** [nairobilug/nairobilug.or.ke#189]
Right now, (I think) the maintainers do this each time there is a PR/change to be made

`Merge PR -> 👨‍💻 Pull repo -> generate site -> 🥱 push to gh-pages -> site deployed`

I propose we use some sort of automation so the work-flow looks like this.

`Merge PR -> 🤖 Automation  🤖 -> site deployed`

## Option 1. [Netlify](https://www.netlify.com/)

The services focus on making static site hosting easier.

#### Advantages

* Git integration
* Deploy previews - All Commits & PRs get unique permanent urls that anyone can see.
* Automatic builds - Merging a PR is enough to apply changes to the site.

#### Disadvantages

* Only 1 admin per site in the free tier

### Demo

[Example PR with preview url](https://github.com/IanMuchina/nairobilug/pull/1)

Other providers

* [vercel](https://vercel.com/) - Mostly same features & restricions

* [render](https://render.com/pricing) - Mostly same + Free for teams 
* [DigitalOcean App platform](https://www.digitalocean.com/docs/app-platform/) - Free, previews yet to be implemented , unlimited collaborators

## Option 2.  github-pages + github actions

[Github actions](https://github.com/features/actions) can be used to automate almost anything.

#### Advantages
* Free & part of github
* quickest setup
* Lots of  community-created actions like [this](https://github.com/marketplace/actions/github-pages-pelican-build-action)
#### Disadvantages

* No deploy previews

### Demo

[Example site](https://test.muchina.gq) 
[`actions.yml`](https://github.com/IanMuchina/nairobilug/blob/gh-actions/.github/workflows/pages.yml) fotr the site

 If we end up using github actions, we can still use netlify just for checks & deploy previews.

**Comment by jasonrogena** [comment]
@IanMuchina for simplicity’s sake, "Option 2" seems viable to me.

**Comment by bkmgit** [comment]
@jasonrogena @IanMuchina Possibly ok without previews. One can update the site as needed if some errors are found. Actions are well documented:
https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/introduction-to-github-actions 
Possible steps to put in an action (not tested, but may help get started) is in #190

**Comment by IanMuchina** [comment]
@bkmgit  this should work.

```yaml
name: Update Website

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true # Gets all submodules
          fetch-depth: 0 # get entire history

      - name: Python
        uses: actions/setup-python@v2     
        with:
          python-version: 3.8

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Generate site 
        run: make html

      - name: push output to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
```

https://github.com/peaceiris/actions-gh-pages
